import { readFile, writeFile, mkdir } from "node:fs/promises";
const names = {
  didRegistry: "DIDRegistry",
  identityRegistry: "IdentityAccessRegistry",
  assetNFT: "AssetNFT",
};
const abis = {};
for (const [key, name] of Object.entries(names)) {
  abis[key] = JSON.parse(
    await readFile(`contracts/out/${name}.sol/${name}.json`, "utf8"),
  ).abi;
}
await mkdir("shared", { recursive: true });
await mkdir("frontend/src/generated", { recursive: true });
await writeFile("shared/abis.json", JSON.stringify(abis, null, 2) + "\n");
await writeFile(
  "frontend/src/generated/abis.ts",
  `// Generated by npm run abi. Do not edit.\nexport const abis = ${JSON.stringify(abis, null, 2)} as const;\n`,
);
console.log("Exported three ABIs from compiled artifacts.");
